#Reading in Data

```{r F1}

circuits <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-09-07/circuits.csv')
constructor_results <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-09-07/constructor_results.csv')
constructor_standings <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-09-07/constructor_standings.csv')
constructors <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-09-07/constructors.csv')
driver_standings <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-09-07/driver_standings.csv')
drivers <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-09-07/drivers.csv')
lap_times <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-09-07/lap_times.csv')
pit_stops <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-09-07/pit_stops.csv')
qualifying <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-09-07/qualifying.csv')
races <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-09-07/races.csv')
results <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-09-07/results.csv')
seasons <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-09-07/seasons.csv')
status <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-09-07/status.csv')

```

#Loading Libraries

```{r}
library(dplyr)
library(tidyr)
library(ggplot2)

```

#Joining Tables

```{r}

constructors
results
pit_stops
races
circuits

results_pits = pit_stops %>%
  left_join(results, by = c("raceId", "driverId"), suffix = c("_pit", "_result")) %>%
  left_join(constructors, by = "constructorId") %>%
  left_join(races, by = "raceId") %>%
  left_join(circuits, by = "circuitId") %>%
  select(raceId, driverId, stop, lap, duration, milliseconds_pit, resultId, constructorId, positionOrder, name.x, circuitRef, year)

results_pits

  
```

#Renaming columns, filtering and mutating data


```{r}
colnames(results_pits)[5] = "pit_stop_duration"
colnames(results_pits)[9] = "finish"
colnames(results_pits)[10] = "constructor_name"
colnames(results_pits)[11] = "circuit_name"

results_pits_plot = results_pits %>%
  filter(year > 2011, year < 2021) %>%
  group_by(raceId, driverId) %>%
  mutate(avg_pit = mean(milliseconds_pit)) %>%
  filter(circuit_name == "silverstone") %>%
  filter(constructor_name %in% c("Mercedes", "Ferrari", "Red Bull", "Williams", "McLaren", "Toro Rosso")) %>%
  filter(avg_pit < 40000)

results_pits_plot
```

#Creating plot

```{r}
ggplot(data = results_pits_plot, aes(x = year, y = avg_pit/1000, color = constructor_name)) + 
  geom_point() + 
  geom_line(alpha = 0.8) +
  geom_smooth(method = 'loess', size = 1) +
  labs(x = "Year", 
       y = "Avg Pit Stop Time (seconds)", 
       title = "Who's the Fastest?", 
       subtitle = "Average pit stop time at the historic Silverstone Circuit over the past 10 years of F1 races",
       caption = "Source: Ergast API and FiveThirty Eight") +
  facet_wrap( ~ constructor_name) +
  scale_x_continuous(n.breaks = 5) +
  scale_colour_manual(values = c("Ferrari" = "#faed00", 
                                 "McLaren" = "#272525", 
                                 "Mercedes" = "#a6b5b5", 
                                 "Williams" = "#62c2ea", 
                                 "Red Bull" = "#ea1c2d",
                                 "Toro Rosso" = "#9b9fa1")) +
  theme_bw() +
  theme(legend.position = "None", 
        strip.text = element_text(size=12), 
        plot.title = element_text(size=16), 
        plot.subtitle = element_text(size = 10),
        plot.caption = element_text(color = "#787878"))
```







